# This is a basic workflow to help you get started with Actions

name: CI

on:
  repository_dispatch:
    types: [redoc_update]

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name:
        if: github.event_name == 'repository_dispatch'
        run: echo "Trigged from ${{ github.event.client_payload.repo }}"
